server:
  port: 8080

spring:
  application:
    name: "accounts"

#  reading config from config server
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071/}
#    import: configserver:http://localhost:8071/

#  datasource:
#    url: jdbc:mysql://localhost:3307/accountsdb
#    username: root
#    password: root

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/accountsdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    show-sql: true

  sql:
    init:
      mode: always
  # setting sql init mode in spring.sql.init.mode section to run the schema.sql file to create tables,
  # as mysql doesn't run the schema.sql automatically

#  spring profile activate sequentially, means the last mentioned one is replacing other
#  Example => active: prod, qa | here qa will get the highest priority, as it is in the last sequence
#  Example => active: qa, prod | here prod will get the highest priority, as it is in the last sequence

  profiles:
    active: prod

springdoc:
  swagger-ui:
    path: /swagger


# Actuator properties
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
