server:
  port: 8080

spring:
  application:
    name: "accounts"

#  reading config from config server
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071/}
#    import: configserver:http://localhost:8071/

#  datasource:
#    url: jdbc:mysql://localhost:3307/accountsdb
#    username: root
#    password: root

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/accountsdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    show-sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  sql:
    init:
      mode: always
  # setting sql init mode in spring.sql.init.mode section to run the schema.sql file to create tables,
  # as mysql doesn't run the schema.sql automatically

#  spring profile activate sequentially, means the last mentioned one is replacing other
#  Example => active: prod, qa | here qa will get the highest priority, as it is in the last sequence
#  Example => active: qa, prod | here prod will get the highest priority, as it is in the last sequence

  profiles:
    active: prod

springdoc:
  swagger-ui:
    path: /swagger

build:
  version: "3.0"

# Actuator properties
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info: # enable /actuator/info endpoint
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown: # this is for deregistering from eureka server
      enabled: true

# deregistering from eureka server
endpoints:
  shutdown:
    enabled: true

# Eureka properties
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/ # eureka microservices url


# Setting some accounts microservices related properties to view in the eureka dashboard
# Also, this info related information is also found in the actuator related endpoints
# To view it in the actuator endpoint, we have to enable it in the actuator, it will show in the status link of eureka dashboard
info:
  app:
    name: "accounts"
    description: "Accounts Microservices"
    version: "1.0.0"


# Resiliency related properties | circuit breaker pattern
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000


# Resiliency related properties | retry pattern
resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      waitDuration: 10
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException