build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related PROD APIs "
  contactDetails:
    name: "Trin - Manager"
    email: "trin@eazybank.com"
  onCallSupport:
    - (777) 987846-2357
    - (777) 68456-8644