build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Smita - QA"
    email: "smita@eazybank.com"
  onCallSupport:
    - (666) 673-23523
    - (666) 234-34621